apiVersion: v1
kind: ServiceAccount
metadata:
  name: imager-orchestrator
  namespace: imager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imager-orchestrator-cluster
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imager-orchestrator-cluster
subjects:
  - kind: ServiceAccount
    name: imager-orchestrator
    namespace: imager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imager-orchestrator-cluster
