apiVersion: apps/v1
kind: Deployment
metadata:
  name: imager-orchestrator
  namespace: imager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imager-orchestrator
  template:
    metadata:
      labels:
        app: imager-orchestrator
    spec:
      serviceAccountName: imager-orchestrator
      containers:
        - name: orchestrator
          image: imager/orchestrator:local
          imagePullPolicy: IfNotPresent
          args:
            - -listen-port=8099
            - -target-mode=pod
            - -target-namespace=imagerdemo
            - -target-deployment=sumservice
            - -target-port-name=http
            - -target-scheme=http
            - -request-source-type=random-sum
            - -random-sum-path=/sum
            - -random-sum-min=1
            - -random-sum-max=1000
            - -load-calculator=step
            - -min-rps=10
            - -max-rps=500
            - -step-rps=10
            - -schedule-interval=1s
            - -job-duration=1s
            - -metrics-poll-interval=5s
            - -in-cluster=true
          ports:
            - name: http
              containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: imager-orchestrator
  namespace: imager
spec:
  selector:
    app: imager-orchestrator
  ports:
    - name: http
      port: 8099
      targetPort: http
