apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-imager.yaml
  - namespace-imagerdemo.yaml
  - sumservice.yaml
  - imager-rbac.yaml
  - imager-orchestrator.yaml
  - imager-executor.yaml
