apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: imager
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap-requests.yaml
  - test-service.yaml
  - orchestrator-pod-mode.yaml
  - executor.yaml
